name:                 HoareCost
version:              0.1.0.0
visibility:           public
id:                   HoareCost-0.1.0.0-inplace
key:                  HoareCost-0.1.0.0-inplace
maintainer:           gabrielsaldanha373@gmail.com
author:               DisistiNao
abi:                  inplace
exposed:              True
exposed-modules:      Hoare Imp Lexer.Lexer Parser.Arith Syntax Variables
import-dirs:
    /home/gabriel/Documents/Monografia/HoareCost/dist-newstyle/build/x86_64-linux/ghc-8.8.4/HoareCost-0.1.0.0/build

library-dirs:
    /home/gabriel/Documents/Monografia/HoareCost/dist-newstyle/build/x86_64-linux/ghc-8.8.4/HoareCost-0.1.0.0/build

dynamic-library-dirs:
    /home/gabriel/Documents/Monografia/HoareCost/dist-newstyle/build/x86_64-linux/ghc-8.8.4/HoareCost-0.1.0.0/build

data-dir:             /home/gabriel/Documents/Monografia/HoareCost
hs-libraries:         HSHoareCost-0.1.0.0-inplace
depends:              array-0.5.4.0 base-4.13.0.0 containers-0.6.2.1
haddock-interfaces:
    /home/gabriel/Documents/Monografia/HoareCost/dist-newstyle/build/x86_64-linux/ghc-8.8.4/HoareCost-0.1.0.0/doc/html/HoareCost/HoareCost.haddock

haddock-html:
    /home/gabriel/Documents/Monografia/HoareCost/dist-newstyle/build/x86_64-linux/ghc-8.8.4/HoareCost-0.1.0.0/doc/html/HoareCost
